### ISSUE TITLE
Invalid syntax on printing pilot.

### ISSUE THREAD

**Issue by philderbeast** [kuaka/fsdb_igc#1]
```
> nix-shell -p 'python3.withPackages(ps: with ps; [ argparse lxml ])'
[nix-shell:~/dev/src/blockscope/2018-forbes-flatlands-score]$ python fsdb_igc.py forbes2018.fsdb
  File "<fstring>", line 1
    (pil_id=)
           ^
SyntaxError: invalid syntax
[nix-shell:~/dev/src/blockscope/2018-forbes-flatlands-score]$ python
Python 3.6.6 (default, Aug 11 2018, 09:13:30)
[GCC 4.2.1 Compatible Clang 5.0.2 (tags/RELEASE_502/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml.etree as ET
>>> import os, argparse
>>> import shutil
>>> exit()
```

If I comment out the following line then I don't get this error:
https://github.com/kuaka/fsdb_igc/blob/b41fa5f303f609fbfea09e94a3214539cda956bc/fsdb_igc.py#L56

```
[nix-shell:~/dev/src/blockscope/2018-forbes-flatlands-score]$ python fsdb_igc.py forbes2018.fsdb
{'4': 'Frank Chetcuti', ..., '108': 'Peter Adriaans'}
Task 1
task 2
Task 3
Task 4
Task 5
Task 6
Task 7
```

**Comment by kuaka** [comment]
This is a python 3.8 feature. Rather than specifying v3.8 as a requirement I will probably make this line 3.6 compatible and specify that as a requirement.

**Comment by kuaka** [comment]
> This is a python 3.8 feature. Rather than specifying v3.8 as a requirement I will probably make this line 3.6 compatible and specify that as a requirement.

done with https://github.com/kuaka/fsdb_igc/commit/77d14d244fcd14b9ca8cafaade39331ba1ac284e

**Comment by philderbeast** [comment]
FYI, I upgraded my nix installation and channel and am now on python version 3.8 within a nix shell. The older nixpkgs-19.09 channel I was on had version 3.6 of python.

I followed the uninstall and quick install [instructions](https://nixos.org/download.html), deleted all existing channels and then added unstable.

```
> sudo nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
> nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
> nix-shell -p 'python3.withPackages(ps: with ps; [ lxml ])'
> [nix-shell:~/dev/src/blockscope/2018-forbes-flatlands-score]$ python --version
Python 3.8.6
> python fsdb_igc.py forbes2018.fsdb
...
```
