### ISSUE TITLE
The pilot name is not unique in fsdb.

### ISSUE THREAD

**Issue by philderbeast** [kuaka/fsdb_igc#2]
The `<FsParticipant id="8" name="Gordon Rigg"/>` for task 1 gets written to `output/task 1/Gordon_Rigg.igc`. This `FsParticipant/@name` is not unique. Please include the pilot's `FsParticipant/@id` into the output file name.

**Comment by kuaka** [comment]
@philderbeast I have been looking for two pilots named Gordon Rigg in the file and in the results. I haven't been able to find more than 1. Now I am thinking you are speaking in general.
I will add the id.

**Comment by kuaka** [comment]
have pushed https://github.com/kuaka/fsdb_igc/commit/ac3f2cc05b19f935a3d18e7c7d35ced3acd270a3 which adds the id.

**Comment by philderbeast** [comment]
> I have been looking for two pilots named Gordon Rigg in the file and in the results. I haven't been able to find more than 1. Now I am thinking you are speaking in general.

I'm pretty sure there's only one Gordon Rigg.

**Comment by kuaka** [comment]
ok, thanks. It was unclear, I thought there was an issue with 2 pilots with the same name.
